using CarboniteXmlParser.XmlEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace FileCreatorTool
{
    class BackupFile
    {
        public int MessageCount {
            get {
                return TextMessages.Count();
            }
        }

        public DateTime BackupDate { get; set; }

        public IEnumerable<Sms> TextMessages { get; set; }

        public BackupFile()
        {
            TextMessages = new List<Sms>();
        }

        private static string DateToTimeStamp(DateTime date)
        {
            return ((DateTimeOffset)date).ToUnixTimeSeconds().ToString();
        }

        public void WriteXml(XmlWriter writer)
        {
            writer.WriteComment($"Generated by Ryan's File Creation Tool on {DateTime.Now.ToString()}.");
            writer.WriteStartElement("smses");
            writer.WriteAttributeString("count", MessageCount.ToString());
            writer.WriteAttributeString("backup_date", DateToTimeStamp(BackupDate));

            if (TextMessages != null)
            {
                foreach (var sms in TextMessages)
                {
                    writer.WriteStartElement("sms");
                    writer.WriteAttributeString("protocol", sms.Protocol.ToString());
                    writer.WriteAttributeString("address", sms.Address);
                    writer.WriteAttributeString("date", DateToTimeStamp(sms.Date));
                    writer.WriteAttributeString("type", ((int)sms.MessageType).ToString());
                    writer.WriteAttributeString("subject", sms.Subject);
                    writer.WriteAttributeString("body", sms.Body);
                    writer.WriteAttributeString("contact_name", sms.ContactName);
                    writer.WriteEndElement();
                }
            }

            writer.WriteEndElement();
        }
    }
}
