//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Key { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string MimeType { get; set; }
        public int MessageKey { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
