//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAddress
    {
        public string MessageId { get; set; }
        public string Number { get; set; }
        public string ContactName { get; set; }
        public byte Direction { get; set; }
    }
}
