//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string MessageId { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Body { get; set; }
        public MessageType MessageType { get; set; }
        public byte Status { get; set; }
    }
}
