//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Staging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StagingContext : DbContext
    {
        public StagingContext()
            : base("name=StagingContext")
        {
             this.Configuration.AutoDetectChangesEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<MessageAddress> MessageAddresses { get; set; }
    
        public virtual int USP_Merge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Merge");
        }
    
        public virtual int USP_Truncate_Staging()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Truncate_Staging");
        }
    }
}
