//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImport.Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.MessageAddresses = new HashSet<MessageAddress>();
        }
    
        public long Key { get; set; }
        public string Number { get; set; }
        public string ContactName { get; set; }
    
        public virtual ICollection<MessageAddress> MessageAddresses { get; set; }
    }
}
