//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.MessageAddresses = new HashSet<MessageAddress>();
            this.MessageAttachments = new HashSet<MessageAttachment>();
        }
    
        public long Key { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Body { get; set; }
        public MessageImport.Data.MessageType MessageType { get; set; }
        public sbyte Status { get; set; }
        public long FromAddressKey { get; set; }
        public string MessageId { get; set; }
    
        public virtual Address FromAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageAddress> MessageAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageAttachment> MessageAttachments { get; set; }
    }
}
