//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImport.Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAddress
    {
        public long Key { get; set; }
        public long MessageKey { get; set; }
        public long AddressKey { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Message Message { get; set; }
    }
}
