//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImport.Data.Staging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageAddresses = new HashSet<MessageAddress>();
            this.MessageAttachments = new HashSet<MessageAttachment>();
        }
    
        public long Key { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Body { get; set; }
        public sbyte MessageType { get; set; }
        public sbyte Status { get; set; }
    
        public virtual ICollection<MessageAddress> MessageAddresses { get; set; }
        public virtual ICollection<MessageAttachment> MessageAttachments { get; set; }
    }
}
