//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageImport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MessageImport.Data.Staging;
    
    public partial class StagingEntities : DbContext
    {
        public StagingEntities()
            : base("name=StagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageAddress> MessageAddresses { get; set; }
        public DbSet<MessageAttachment> MessageAttachments { get; set; }
    }
}
